### PR TITLE
Disable callback features in 0.5

### PR DESCRIPTION
**Pull request by jdlangs**
This is really just to get the tests passing again even though the package remains crippled.

### CODE REVIEW

**Comment by tkelman** [comment]
was 3692 when threads were enabled by default?

**Comment by jdlangs** [comment]
Yes, that's what `commit-name.sh` gave me for [53665868](https://github.com/JuliaLang/julia/pull/15997/commits/53665868270c5202a46e30bae7412faf13a9eabe)

**Comment by tkelman** [comment]
usually best to use the merge commit for that, but i doubt anyone will notice the exact difference.

**Comment by jdlangs** [comment]
Noted for future uses.

**Pull request merged**
